
name: Deploy to Development Server

on:
  pull_request:
    branches:
      - development
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Upload image to DEV server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remote-ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_IP }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: 22
          script: cd /var/www/2dev4pro-group && git pull && pm2 restart group_telegram
